name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: ggingmin-ct/test
          stage: main
          yaml: >
            name: slackbot-chatgpt

            app: node@16

            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: SLACK_BOT_TOKEN
                  value: ${{ secrets.SLACK_BOT_TOKEN }}
                - name: SLACK_SIGNING_SECRET
                  value: ${{ secrets.SLACK_SIGNING_SECRET }}
                - name: OPENAI_API_KEY
                  secret: openaiApiKey
              ports: 3000
              install: yarn
              start: yarn start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: slackbot-js
